language: php
php:
  - 5.6
  - hhvm

env:
  - DB=sqlite

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - DB_CONNECTOIN='test'
  - sqlite3 storage/database/database_test.sqlite .database
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
